language: c

before_install:
  - echo "START"

install: make get-deps
# install: true
# make && make test

compiler:
  - clang
  - gcc

script: "./runner.sh"


# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
    - stable

