language: c

before_install:
  - echo "START"

before_script:
  - chmod +x runner.sh

install: make get-deps
# install: true
# make && make test

compiler:
  - clang
  - gcc

script: "./runner.sh"


# blacklist
branches:
  except:
    - legacy
    - experimental

# whitelist
branches:
  only:
    - master
    - stable

notifications:
  email:
    - wjuma@students.usiu.ac.ke
